"""sessao cancelada com motivo

Revision ID: 730691b20ec3
Revises: 9d3e1c7a4f52
Create Date: 2026-08-16 17:47:05.633891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730691b20ec3'
down_revision: Union[str, Sequence[str], None] = '9d3e1c7a4f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('showings', sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showings', 'cancellation_reason')
    op.drop_column('showings', 'cancelled_at')
    # ### end Alembic commands ###
