"""municipio do IBGE no cinema

Revision ID: c45d37a00d2e
Revises: 82ec8644b13c
Create Date: 2026-08-17 22:24:43.644940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45d37a00d2e'
down_revision: Union[str, Sequence[str], None] = '82ec8644b13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nasce anulável para que a coluna exista antes de haver valor: o código
    # não sai de lugar nenhum do banco, precisa ser preenchido a partir do
    # par (cidade, UF) que já está gravado.
    op.add_column('venues', sa.Column('city_ibge_id', sa.Integer(), nullable=True))

    # Mapa estático em vez de consulta ao IBGE: migration que depende de rede
    # falha em ambiente sem saída para a internet, e o resultado deixaria de
    # ser reproduzível. Os pares abaixo são os que existem no cenário
    # semeado; qualquer outro é apanhado pela checagem logo adiante.
    for codigo, cidade, uf in [
        (3550308, 'São Paulo', 'SP'),
        (3304557, 'Rio de Janeiro', 'RJ'),
    ]:
        op.execute(sa.text(
            "UPDATE venues SET city_ibge_id = :codigo "
            "WHERE city = :cidade AND state = :uf"
        ).bindparams(codigo=codigo, cidade=cidade, uf=uf))

    # Falha alto em vez de deixar linha sem código: uma cidade fora do mapa
    # viraria um cinema invisível para o filtro do catálogo, e o sintoma
    # apareceria muito longe da causa.
    restantes = op.get_bind().execute(sa.text(
        "SELECT string_agg(DISTINCT city || '/' || state, ', ') "
        "FROM venues WHERE city_ibge_id IS NULL")).scalar()
    if restantes:
        raise RuntimeError(
            f"Cidades sem código do IBGE nesta base: {restantes}. "
            "Acrescente o par ao mapa desta migration antes de aplicá-la."
        )

    op.alter_column('venues', 'city_ibge_id', nullable=False)
    op.create_index(op.f('ix_venues_city_ibge_id'), 'venues', ['city_ibge_id'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_city_ibge_id'), table_name='venues')
    op.drop_column('venues', 'city_ibge_id')
    # ### end Alembic commands ###
