"""data de cancelamento do ingresso

Revision ID: ec9821a0ac58
Revises: 730691b20ec3
Create Date: 2026-08-16 18:29:31.416671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9821a0ac58'
down_revision: Union[str, Sequence[str], None] = '730691b20ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'cancelled_at')
    # ### end Alembic commands ###
